### ISSUE TITLE
Application and container not available in configure method of command

### ISSUE THREAD

**Issue by raphaelstolt** [Cilex/console-service-provider#8]
```
<?php

use Symfony\Component\Console\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class SomeCommand extends Command
{
    protected function configure()
    {
        $application = $this->getApplication(); // renders null but might hold values (i.e. from a config file) needed for command configuration
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        // Direct access to the Container.
        $container = $this->getApplication()->getContainer();

        // Direct access to a service.
       $service = $this->getApplication->getService('some.service');
   }
}
```

**Comment by simensen** [comment]
The problem is that `configure` is called in the constructor of `Command` as seen [here](https://github.com/symfony/Console/blob/master/Command/Command.php#L68). The `Application` is set on the `Command` well after the `Command` is created as seen [here](https://github.com/symfony/Console/blob/master/Application.php#L402).

If you absolutely have to have `Application` in your `Command` you'd have to override the constructor to accept the `Application` and set it before calling `parent::__construct()`. It is not pretty at all, but the only way you can really do it. Even at that, there might be some weird circular logic that might cause some problems.
